### ISSUE TITLE
more info needed

### ISSUE THREAD

**Issue by ghost** [ichenhe/oc-b760m-13700-6800#2]
hi, can you tell me what works, what not?

- shutdown - does it stay off all night or turns on randomly
- universal clipboard (copy/paste)
- Airdrop
- Handoff
- is WiFi reliable
- Wifi speed over 5G
- USB3 speed MB/sec

or did you maybe replace the Wifi/Bluetooth card with a second-hand Broadcom?

thanks!

**Comment by ichenhe** [comment]
- shutdown: won't auto restart
- universal clipboard / Airdrop / Handoff: I don't have an real apple device
- WiFi: Reliable, can reach the maximum speed of my homeband (300Mbps)
- USB3(typeA/C): can reach the max speed of my usb driver: 460MB/s
- Use default BT/Wifi driver of MSI mother board.

**Comment by ghost** [comment]
thank you !
