### ISSUE TITLE
No WIFI

### ISSUE THREAD

**Issue by kevinwells22** [ichenhe/oc-b760m-13700-6800#3]
Hi, thank you for publishing this, it has been amazing, and very easy for me to up and running.
I have:

Mac OS Sonoma 14.1
MSI MAG Morter Wifi board (BIOS 7E01vM5)
i5-13500
RX 5700
CORSAIR VENGEANCE RGB DDR5 RAM 32GB (2x16GB) 5600MHz

I downloaded your EFI, added my own own serial number, etc, nothing else.
All seems to be working well, except Wifi, which is not working.
Just wanted to check in with you if i should maybe do anything else please?

**Comment by ichenhe** [comment]
Nothing. Please note that this EFI has not been tested on MacOS14. In general, we have to wait for a time before the opencore and kexts can work perfectly on the lateset major os version.

For now I can't give you any suggestions about the wifi issue.

However, based on my experience, try:
- Make sure set BIOS properly
- If you installed both windows and hackintosh: start windows and connect wifi, then shutdown (not restart), and start mac.

**Comment by kevinwells22** [comment]
Thanks for your reply. I updated AirportItlwm.kext to the latest (although it's in BETA), now WIFI is working.
